collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.188172
color:
  saturation: 0.3870968
  brandStrength: 0.6057348
  lightness: 0.5698925
  brandColors:
    - '#E8F2FA'
    - '#1F1616'
    - '#5B4B43'
    - '#AC9988'
    - '#DFFD39'
  rhythmicContrast: 0.5286738
layout_spectrum: 1
name: Chavish
